name: Build Electron App for Windows

on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Instalar dependencias
      run: npm install
      
    - name: Compilar aplicación Electron (solo Windows)
      run: npx electron-builder --win --x64
      
    - name: Subir artefacto portable
      uses: actions/upload-artifact@v4
      with:
        name: Visualizador-BIW-Calidad-Windows
        path: dist/*.exe
        retention-days: 30